/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import file.ManipularArquivos;
import java.awt.Graphics;
import java.awt.Image;
import static java.lang.Boolean.FALSE;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.Icon;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Terreno;
import model.dao.TerrenoDAO;

/**
 *
 * @author ramires
 */
public class TelaTerreno extends javax.swing.JFrame {
    
    public static boolean filtro;
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaTerreno.getModel();
        modelo.setNumRows(0);
        TerrenoDAO tDAO = new TerrenoDAO();
        
        DecimalFormat df = new DecimalFormat("0.00",new DecimalFormatSymbols(new Locale("en","US")));
        
        
        for(Terreno t: tDAO.read()){
            modelo.addRow(new Object[]{
                t.getIdTerreno(),
                t.getNome(),
                t.getArea(),
                t.getEstado(),
                t.getCultura(),
                df.format(t.getGastos())
            });
        }
    }
    
    public void readJTableFiltro(String tipo){
        DefaultTableModel modelo = (DefaultTableModel) tabelaTerreno.getModel();
        modelo.setNumRows(0);
        TerrenoDAO tDAO = new TerrenoDAO();
        
        DecimalFormat df = new DecimalFormat("0.00",new DecimalFormatSymbols(new Locale("en","US")));
        
        
        for(Terreno t: tDAO.readFiltro(tipo)){
            modelo.addRow(new Object[]{
                t.getIdTerreno(),
                t.getNome(),
                t.getArea(),
                t.getEstado(),
                t.getCultura(),
                df.format(t.getGastos())
            });
        }
        //Altera o ícone do botao filtro
        ClassLoader cl = this.getClass().getClassLoader();
        Icon icone = new ImageIcon(cl.getResource("icons/removerFiltro.png"));
        botaoFiltro.setIcon(icone);
        botaoFiltro.setToolTipText("Remover Filtro");
    }

    /**
     * Creates new form TelaTerreno
     */
    public TelaTerreno() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelaTerreno.getModel();
        modelo.setNumRows(0);
        tabelaTerreno.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){

                ClassLoader cl = this.getClass().getClassLoader();

                ImageIcon im = new ImageIcon(cl.getResource("images/bg.jpg"));
                Image i = im.getImage();

                g.drawImage(i,0,0,this.getSize().width,this.getSize().height,this);

            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTerreno = new javax.swing.JTable();
        botaoVoltar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botaoAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoColheita = new javax.swing.JButton();
        botaoVeneno = new javax.swing.JButton();
        botaoPlantio = new javax.swing.JButton();
        botaoFiltro = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Terrenos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        tabelaTerreno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Área", "Estado", "Cultura", "Gastos"
            }
        ));
        tabelaTerreno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaTerreno.setOpaque(false);
        jScrollPane1.setViewportView(tabelaTerreno);

        botaoVoltar.setBackground(new java.awt.Color(51, 153, 255));
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow(1).png"))); // NOI18N
        botaoVoltar.setToolTipText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoEditar.setBackground(new java.awt.Color(51, 153, 255));
        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        botaoEditar.setToolTipText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rubbish.png"))); // NOI18N
        jButton1.setToolTipText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoAdd.setBackground(new java.awt.Color(51, 153, 255));
        botaoAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        botaoAdd.setToolTipText("Adicionar");
        botaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chilanka", 1, 48)); // NOI18N
        jLabel1.setText("Terrenos");

        botaoColheita.setBackground(new java.awt.Color(51, 153, 255));
        botaoColheita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/combine-harvester.png"))); // NOI18N
        botaoColheita.setToolTipText("Colher");
        botaoColheita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoColheitaActionPerformed(evt);
            }
        });

        botaoVeneno.setBackground(new java.awt.Color(51, 153, 255));
        botaoVeneno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/passarVeneno.png"))); // NOI18N
        botaoVeneno.setToolTipText("Passar Veneno");
        botaoVeneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenenoActionPerformed(evt);
            }
        });

        botaoPlantio.setBackground(new java.awt.Color(51, 153, 255));
        botaoPlantio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plant.png"))); // NOI18N
        botaoPlantio.setToolTipText("Plantar");
        botaoPlantio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPlantioActionPerformed(evt);
            }
        });

        botaoFiltro.setBackground(new java.awt.Color(51, 153, 255));
        botaoFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/filter.png"))); // NOI18N
        botaoFiltro.setToolTipText("Filtrar");
        botaoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFiltroActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/faq.png"))); // NOI18N
        jButton5.setToolTipText("Ajuda");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(268, 268, 268))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAdd)
                        .addGap(18, 18, 18)
                        .addComponent(botaoFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(botaoEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoColheita)
                        .addGap(18, 18, 18)
                        .addComponent(botaoVeneno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoPlantio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(botaoColheita))
                        .addComponent(botaoVeneno))
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(botaoPlantio)
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoEditar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoFiltro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddActionPerformed
        // TODO add your handling code here:
        TelaAddTerreno.telaTerreno = this;
        
        new TelaAddTerreno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoAddActionPerformed

    private void botaoColheitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoColheitaActionPerformed
        // TODO add your handling code here:
        if(tabelaTerreno.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um Terreno!");
        }
        else{
            if("Limpo".equals(tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 3))){
                JOptionPane.showMessageDialog(null, "O Terreno Está Limpo! Não é Possível Colher!");
            }
            else{
                TelaRegistrarColheita.tTerreno = this;
                TelaRegistrarColheita.idTerreno = (int) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 0);
                TelaRegistrarColheita.nomeT = (String) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 1);
                TelaRegistrarColheita.cultura = (String) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 4);
                TelaRegistrarColheita.preco = Double.parseDouble((String) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 5));
                
                new TelaRegistrarColheita().setVisible(true);
            }
        }
        
    }//GEN-LAST:event_botaoColheitaActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        // TODO add your handling code here:
        if(tabelaTerreno.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um Terreno!");
        }
        else {
            TelaAltTerreno.telaTerreno = this;
            
            //Pegar ID e nome do terreno para alteração
            TelaAltTerreno.idTerrenoAux = (int) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 0);
            TelaAltTerreno.nomeT = (String) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 1);
            
            new TelaAltTerreno().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tabelaTerreno.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um Terreno!");
        }
        else{
            int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja realmente remover o terreno?");
            
            int id = (int) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 0);
            
            if(confirmacao == JOptionPane.YES_OPTION){
                ManipularArquivos manip = new ManipularArquivos();
                String arq_id,arq_nome, arq_area, arq_estado, arq_cultura,arq_gastos;
                arq_id = tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 0).toString();
                arq_nome = tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 1).toString();
                arq_area = tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 2).toString();
                arq_estado = tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 3).toString();
                arq_cultura = tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 4).toString();
                arq_gastos = tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 5).toString();
                manip.ArquivoTerreno(arq_id, arq_nome, arq_area, arq_estado, arq_cultura, arq_gastos);
                TerrenoDAO tDAO = new TerrenoDAO();
                tDAO.remover(id);
                
                readJTable();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoPlantioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPlantioActionPerformed
        // TODO add your handling code here:
        if(tabelaTerreno.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null,"Selecione um Terreno!");
        }else{
            String estado = (String) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 3);
            
            if(estado.equals("Plantado")){
                JOptionPane.showMessageDialog(null, "O Terreno Já Está Plantado!");
            }else{
                TelaAddPlantio.idTerreno = (int) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 0);
                TelaAddPlantio.nometerreno = (String) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 1);
                new TelaAddPlantio().setVisible(true);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_botaoPlantioActionPerformed

    private void botaoVenenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenenoActionPerformed
        // TODO add your handling code here:
        if(tabelaTerreno.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um Terreno!");
        }
        else{
            TelaAddManutTerreno.nomeT = (String) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 1);
            new TelaAddManutTerreno().setVisible(true);
            this.dispose();
            TelaAddManutTerreno.telaTerreno = this;
            TelaAddManutTerreno.idTerreno = (int) tabelaTerreno.getValueAt(tabelaTerreno.getSelectedRow(), 0);
        }
        
    }//GEN-LAST:event_botaoVenenoActionPerformed

    private void botaoFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFiltroActionPerformed
        // TODO add your handling code here:
        if(filtro == FALSE){
            new TelaFiltrarTerreno().setVisible(true);
            TelaFiltrarTerreno.telaT = this;
        }
        else{
            filtro = FALSE;
            ClassLoader cl = this.getClass().getClassLoader();
            Icon icone = new ImageIcon(cl.getResource("icons/filter.png"));
            botaoFiltro.setIcon(icone);
            botaoFiltro.setToolTipText("Filtrar");
            readJTable();
        }
        
    }//GEN-LAST:event_botaoFiltroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new TelaTerrenoAjuda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTerreno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdd;
    private javax.swing.JButton botaoColheita;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoFiltro;
    private javax.swing.JButton botaoPlantio;
    private javax.swing.JButton botaoVeneno;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTerreno;
    // End of variables declaration//GEN-END:variables
}
